// Copyright(C) 2021 Lars Pontoppidan. All rights reserved.
// NOTE this file is auto-generated by cmd/gen_miniaudio_auto.v
module miniaudio

import miniaudio.c

pub const used_import = c.used_import

// C.ma_result
pub enum Result {
	success = 0
	error // TODO add all
}

// DeviceType
pub enum DeviceType {
	playback = C.ma_device_type_playback
	capture = C.ma_device_type_capture
	duplex = 3 // C.ma_device_type_playback | C.ma_device_type_capture, /* 3 */
	loopback = C.ma_device_type_loopback
}

// Format
pub enum Format {
	unknown = C.ma_format_unknown
	u8 = C.ma_format_u8
	s16 = C.ma_format_s16
	s24 = C.ma_format_s24
	s32 = C.ma_format_s32
	f32 = C.ma_format_f32
	count = C.ma_format_count
}

struct C.ma_pcm_converter {}

type PCMConverter = C.ma_pcm_converter

[heap]
struct C.ma_decoder {
pub mut:
	outputFormat     Format // Format
	outputChannels   u32    // u32
	outputSampleRate u32    // u32
}

pub type Decoder = C.ma_decoder

struct C.playback {
pub mut:
	format   Format // Format
	channels u32    // u32
	// channelMap [32 /*C.MA_MAX_CHANNELS*/ ]ma_channel
}

pub type Playback = C.playback

[typedef]
struct C.ma_device {
pub mut:
	pUserData voidptr
	playback  Playback
}

pub type Device = C.ma_device

[typedef]
struct C.ma_context {
	logCallback voidptr // C.ma_log_proc
}

pub type Context = C.ma_context

[typedef]
struct C.ma_context_config {
mut:
	logCallback voidptr // C.ma_log_proc
}

pub type ContextConfig = C.ma_context_config

[typedef]
struct C.ma_mutex {}

pub type Mutex = C.ma_mutex

[typedef]
struct C.ma_decoder_config {
	outputFormat     Format // Format
	outputChannels   u32    // u32
	outputSampleRate u32    // u32
}

pub type DecoderConfig = C.ma_decoder_config

[typedef]
struct C.ma_device_config {
mut:
	deviceType               DeviceType
	sampleRate               u32 // u32
	bufferSizeInFrames       u32 // u32
	bufferSizeInMilliseconds u32 // u32
	periods                  u32 // u32
	performanceProfile       C.ma_performance_profile
	noPreZeroedOutputBuffer  bool
	noClip                   bool
	dataCallback             voidptr // C.ma_device_callback_proc
	stopCallback             voidptr // C.ma_stop_proc
	pUserData                voidptr
	playback                 Playback
}

pub type DeviceConfig = C.ma_device_config

//
// miniaudio.h
//

// MA_API void ma_version(ma_uint32* pMajor, ma_uint32* pMinor, ma_uint32* pRevision);
fn C.ma_version(p_major &u32, p_minor &u32, p_revision &u32)

// MA_API const char* ma_version_string();
fn C.ma_version_string() &char

// MA_API ma_log_callback ma_log_callback_init(ma_log_callback_proc onLog, void* pUserData);
fn C.ma_log_callback_init(on_log C.ma_log_callback_proc, p_user_data voidptr) C.ma_log_callback

// MA_API ma_result ma_log_init(const ma_allocation_callbacks* pAllocationCallbacks, ma_log* pLog);
fn C.ma_log_init(p_allocation_callbacks &C.ma_allocation_callbacks, p_log &C.ma_log) Result

// MA_API void ma_log_uninit(ma_log* pLog);
fn C.ma_log_uninit(p_log &C.ma_log)

// MA_API ma_result ma_log_register_callback(ma_log* pLog, ma_log_callback callback);
fn C.ma_log_register_callback(p_log &C.ma_log, callback C.ma_log_callback) Result

// MA_API ma_result ma_log_unregister_callback(ma_log* pLog, ma_log_callback callback);
fn C.ma_log_unregister_callback(p_log &C.ma_log, callback C.ma_log_callback) Result

// MA_API ma_result ma_log_post(ma_log* pLog, ma_uint32 level, const char* pMessage);
fn C.ma_log_post(p_log &C.ma_log, level u32, p_message charptr) Result

// MA_API ma_result ma_log_postv(ma_log* pLog, ma_uint32 level, const char* pFormat, va_list args);
fn C.ma_log_postv(p_log &C.ma_log, level u32, p_format charptr, args C.va_list) Result

// Skipped:
/*
MA_API ma_result ma_log_postf(ma_log* pLog, ma_uint32 level, const char* pFormat, ...) MA_ATTRIBUTE_FORMAT(3, 4);
*/

// MA_API ma_biquad_config ma_biquad_config_init(ma_format format, ma_uint32 channels, double b0, double b1, double b2, double a0, double a1, double a2);
fn C.ma_biquad_config_init(format Format, channels u32, b0 f64, b1 f64, b2 f64, a0 f64, a1 f64, a2 f64) C.ma_biquad_config

// MA_API ma_result ma_biquad_init(const ma_biquad_config* pConfig, ma_biquad* pBQ);
fn C.ma_biquad_init(p_config &C.ma_biquad_config, p_b_q &C.ma_biquad) Result

// MA_API ma_result ma_biquad_reinit(const ma_biquad_config* pConfig, ma_biquad* pBQ);
fn C.ma_biquad_reinit(p_config &C.ma_biquad_config, p_b_q &C.ma_biquad) Result

// MA_API ma_result ma_biquad_process_pcm_frames(ma_biquad* pBQ, void* pFramesOut, const void* pFramesIn, ma_uint64 frameCount);
fn C.ma_biquad_process_pcm_frames(p_b_q &C.ma_biquad, p_frames_out voidptr, p_frames_in voidptr, frame_count u64) Result

// MA_API ma_uint32 ma_biquad_get_latency(const ma_biquad* pBQ);
fn C.ma_biquad_get_latency(p_b_q &C.ma_biquad) u32

// MA_API ma_lpf1_config ma_lpf1_config_init(ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double cutoffFrequency);
fn C.ma_lpf1_config_init(format Format, channels u32, sample_rate u32, cutoff_frequency f64) C.ma_lpf1_config

// MA_API ma_lpf2_config ma_lpf2_config_init(ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double cutoffFrequency, double q);
fn C.ma_lpf2_config_init(format Format, channels u32, sample_rate u32, cutoff_frequency f64, q f64) C.ma_lpf2_config

// MA_API ma_result ma_lpf1_init(const ma_lpf1_config* pConfig, ma_lpf1* pLPF);
fn C.ma_lpf1_init(p_config &C.ma_lpf1_config, p_l_p_f &C.ma_lpf1) Result

// MA_API ma_result ma_lpf1_reinit(const ma_lpf1_config* pConfig, ma_lpf1* pLPF);
fn C.ma_lpf1_reinit(p_config &C.ma_lpf1_config, p_l_p_f &C.ma_lpf1) Result

// MA_API ma_result ma_lpf1_process_pcm_frames(ma_lpf1* pLPF, void* pFramesOut, const void* pFramesIn, ma_uint64 frameCount);
fn C.ma_lpf1_process_pcm_frames(p_l_p_f &C.ma_lpf1, p_frames_out voidptr, p_frames_in voidptr, frame_count u64) Result

// MA_API ma_uint32 ma_lpf1_get_latency(const ma_lpf1* pLPF);
fn C.ma_lpf1_get_latency(p_l_p_f &C.ma_lpf1) u32

// MA_API ma_result ma_lpf2_init(const ma_lpf2_config* pConfig, ma_lpf2* pLPF);
fn C.ma_lpf2_init(p_config &C.ma_lpf2_config, p_l_p_f &C.ma_lpf2) Result

// MA_API ma_result ma_lpf2_reinit(const ma_lpf2_config* pConfig, ma_lpf2* pLPF);
fn C.ma_lpf2_reinit(p_config &C.ma_lpf2_config, p_l_p_f &C.ma_lpf2) Result

// MA_API ma_result ma_lpf2_process_pcm_frames(ma_lpf2* pLPF, void* pFramesOut, const void* pFramesIn, ma_uint64 frameCount);
fn C.ma_lpf2_process_pcm_frames(p_l_p_f &C.ma_lpf2, p_frames_out voidptr, p_frames_in voidptr, frame_count u64) Result

// MA_API ma_uint32 ma_lpf2_get_latency(const ma_lpf2* pLPF);
fn C.ma_lpf2_get_latency(p_l_p_f &C.ma_lpf2) u32

// MA_API ma_lpf_config ma_lpf_config_init(ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double cutoffFrequency, ma_uint32 order);
fn C.ma_lpf_config_init(format Format, channels u32, sample_rate u32, cutoff_frequency f64, order u32) C.ma_lpf_config

// MA_API ma_result ma_lpf_init(const ma_lpf_config* pConfig, ma_lpf* pLPF);
fn C.ma_lpf_init(p_config &C.ma_lpf_config, p_l_p_f &C.ma_lpf) Result

// MA_API ma_result ma_lpf_reinit(const ma_lpf_config* pConfig, ma_lpf* pLPF);
fn C.ma_lpf_reinit(p_config &C.ma_lpf_config, p_l_p_f &C.ma_lpf) Result

// MA_API ma_result ma_lpf_process_pcm_frames(ma_lpf* pLPF, void* pFramesOut, const void* pFramesIn, ma_uint64 frameCount);
fn C.ma_lpf_process_pcm_frames(p_l_p_f &C.ma_lpf, p_frames_out voidptr, p_frames_in voidptr, frame_count u64) Result

// MA_API ma_uint32 ma_lpf_get_latency(const ma_lpf* pLPF);
fn C.ma_lpf_get_latency(p_l_p_f &C.ma_lpf) u32

// MA_API ma_hpf1_config ma_hpf1_config_init(ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double cutoffFrequency);
fn C.ma_hpf1_config_init(format Format, channels u32, sample_rate u32, cutoff_frequency f64) C.ma_hpf1_config

// MA_API ma_hpf2_config ma_hpf2_config_init(ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double cutoffFrequency, double q);
fn C.ma_hpf2_config_init(format Format, channels u32, sample_rate u32, cutoff_frequency f64, q f64) C.ma_hpf2_config

// MA_API ma_result ma_hpf1_init(const ma_hpf1_config* pConfig, ma_hpf1* pHPF);
fn C.ma_hpf1_init(p_config &C.ma_hpf1_config, p_h_p_f &C.ma_hpf1) Result

// MA_API ma_result ma_hpf1_reinit(const ma_hpf1_config* pConfig, ma_hpf1* pHPF);
fn C.ma_hpf1_reinit(p_config &C.ma_hpf1_config, p_h_p_f &C.ma_hpf1) Result

// MA_API ma_result ma_hpf1_process_pcm_frames(ma_hpf1* pHPF, void* pFramesOut, const void* pFramesIn, ma_uint64 frameCount);
fn C.ma_hpf1_process_pcm_frames(p_h_p_f &C.ma_hpf1, p_frames_out voidptr, p_frames_in voidptr, frame_count u64) Result

// MA_API ma_uint32 ma_hpf1_get_latency(const ma_hpf1* pHPF);
fn C.ma_hpf1_get_latency(p_h_p_f &C.ma_hpf1) u32

// MA_API ma_result ma_hpf2_init(const ma_hpf2_config* pConfig, ma_hpf2* pHPF);
fn C.ma_hpf2_init(p_config &C.ma_hpf2_config, p_h_p_f &C.ma_hpf2) Result

// MA_API ma_result ma_hpf2_reinit(const ma_hpf2_config* pConfig, ma_hpf2* pHPF);
fn C.ma_hpf2_reinit(p_config &C.ma_hpf2_config, p_h_p_f &C.ma_hpf2) Result

// MA_API ma_result ma_hpf2_process_pcm_frames(ma_hpf2* pHPF, void* pFramesOut, const void* pFramesIn, ma_uint64 frameCount);
fn C.ma_hpf2_process_pcm_frames(p_h_p_f &C.ma_hpf2, p_frames_out voidptr, p_frames_in voidptr, frame_count u64) Result

// MA_API ma_uint32 ma_hpf2_get_latency(const ma_hpf2* pHPF);
fn C.ma_hpf2_get_latency(p_h_p_f &C.ma_hpf2) u32

// MA_API ma_hpf_config ma_hpf_config_init(ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double cutoffFrequency, ma_uint32 order);
fn C.ma_hpf_config_init(format Format, channels u32, sample_rate u32, cutoff_frequency f64, order u32) C.ma_hpf_config

// MA_API ma_result ma_hpf_init(const ma_hpf_config* pConfig, ma_hpf* pHPF);
fn C.ma_hpf_init(p_config &C.ma_hpf_config, p_h_p_f &C.ma_hpf) Result

// MA_API ma_result ma_hpf_reinit(const ma_hpf_config* pConfig, ma_hpf* pHPF);
fn C.ma_hpf_reinit(p_config &C.ma_hpf_config, p_h_p_f &C.ma_hpf) Result

// MA_API ma_result ma_hpf_process_pcm_frames(ma_hpf* pHPF, void* pFramesOut, const void* pFramesIn, ma_uint64 frameCount);
fn C.ma_hpf_process_pcm_frames(p_h_p_f &C.ma_hpf, p_frames_out voidptr, p_frames_in voidptr, frame_count u64) Result

// MA_API ma_uint32 ma_hpf_get_latency(const ma_hpf* pHPF);
fn C.ma_hpf_get_latency(p_h_p_f &C.ma_hpf) u32

// MA_API ma_bpf2_config ma_bpf2_config_init(ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double cutoffFrequency, double q);
fn C.ma_bpf2_config_init(format Format, channels u32, sample_rate u32, cutoff_frequency f64, q f64) C.ma_bpf2_config

// MA_API ma_result ma_bpf2_init(const ma_bpf2_config* pConfig, ma_bpf2* pBPF);
fn C.ma_bpf2_init(p_config &C.ma_bpf2_config, p_b_p_f &C.ma_bpf2) Result

// MA_API ma_result ma_bpf2_reinit(const ma_bpf2_config* pConfig, ma_bpf2* pBPF);
fn C.ma_bpf2_reinit(p_config &C.ma_bpf2_config, p_b_p_f &C.ma_bpf2) Result

// MA_API ma_result ma_bpf2_process_pcm_frames(ma_bpf2* pBPF, void* pFramesOut, const void* pFramesIn, ma_uint64 frameCount);
fn C.ma_bpf2_process_pcm_frames(p_b_p_f &C.ma_bpf2, p_frames_out voidptr, p_frames_in voidptr, frame_count u64) Result

// MA_API ma_uint32 ma_bpf2_get_latency(const ma_bpf2* pBPF);
fn C.ma_bpf2_get_latency(p_b_p_f &C.ma_bpf2) u32

// MA_API ma_bpf_config ma_bpf_config_init(ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double cutoffFrequency, ma_uint32 order);
fn C.ma_bpf_config_init(format Format, channels u32, sample_rate u32, cutoff_frequency f64, order u32) C.ma_bpf_config

// MA_API ma_result ma_bpf_init(const ma_bpf_config* pConfig, ma_bpf* pBPF);
fn C.ma_bpf_init(p_config &C.ma_bpf_config, p_b_p_f &C.ma_bpf) Result

// MA_API ma_result ma_bpf_reinit(const ma_bpf_config* pConfig, ma_bpf* pBPF);
fn C.ma_bpf_reinit(p_config &C.ma_bpf_config, p_b_p_f &C.ma_bpf) Result

// MA_API ma_result ma_bpf_process_pcm_frames(ma_bpf* pBPF, void* pFramesOut, const void* pFramesIn, ma_uint64 frameCount);
fn C.ma_bpf_process_pcm_frames(p_b_p_f &C.ma_bpf, p_frames_out voidptr, p_frames_in voidptr, frame_count u64) Result

// MA_API ma_uint32 ma_bpf_get_latency(const ma_bpf* pBPF);
fn C.ma_bpf_get_latency(p_b_p_f &C.ma_bpf) u32

// MA_API ma_notch2_config ma_notch2_config_init(ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double q, double frequency);
fn C.ma_notch2_config_init(format Format, channels u32, sample_rate u32, q f64, frequency f64) C.ma_notch2_config

// MA_API ma_result ma_notch2_init(const ma_notch2_config* pConfig, ma_notch2* pFilter);
fn C.ma_notch2_init(p_config &C.ma_notch2_config, p_filter &C.ma_notch2) Result

// MA_API ma_result ma_notch2_reinit(const ma_notch2_config* pConfig, ma_notch2* pFilter);
fn C.ma_notch2_reinit(p_config &C.ma_notch2_config, p_filter &C.ma_notch2) Result

// MA_API ma_result ma_notch2_process_pcm_frames(ma_notch2* pFilter, void* pFramesOut, const void* pFramesIn, ma_uint64 frameCount);
fn C.ma_notch2_process_pcm_frames(p_filter &C.ma_notch2, p_frames_out voidptr, p_frames_in voidptr, frame_count u64) Result

// MA_API ma_uint32 ma_notch2_get_latency(const ma_notch2* pFilter);
fn C.ma_notch2_get_latency(p_filter &C.ma_notch2) u32

// MA_API ma_peak2_config ma_peak2_config_init(ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double gainDB, double q, double frequency);
fn C.ma_peak2_config_init(format Format, channels u32, sample_rate u32, gain_d_b f64, q f64, frequency f64) C.ma_peak2_config

// MA_API ma_result ma_peak2_init(const ma_peak2_config* pConfig, ma_peak2* pFilter);
fn C.ma_peak2_init(p_config &C.ma_peak2_config, p_filter &C.ma_peak2) Result

// MA_API ma_result ma_peak2_reinit(const ma_peak2_config* pConfig, ma_peak2* pFilter);
fn C.ma_peak2_reinit(p_config &C.ma_peak2_config, p_filter &C.ma_peak2) Result

// MA_API ma_result ma_peak2_process_pcm_frames(ma_peak2* pFilter, void* pFramesOut, const void* pFramesIn, ma_uint64 frameCount);
fn C.ma_peak2_process_pcm_frames(p_filter &C.ma_peak2, p_frames_out voidptr, p_frames_in voidptr, frame_count u64) Result

// MA_API ma_uint32 ma_peak2_get_latency(const ma_peak2* pFilter);
fn C.ma_peak2_get_latency(p_filter &C.ma_peak2) u32

// MA_API ma_loshelf2_config ma_loshelf2_config_init(ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double gainDB, double shelfSlope, double frequency);
fn C.ma_loshelf2_config_init(format Format, channels u32, sample_rate u32, gain_d_b f64, shelf_slope f64, frequency f64) C.ma_loshelf2_config

// MA_API ma_result ma_loshelf2_init(const ma_loshelf2_config* pConfig, ma_loshelf2* pFilter);
fn C.ma_loshelf2_init(p_config &C.ma_loshelf2_config, p_filter &C.ma_loshelf2) Result

// MA_API ma_result ma_loshelf2_reinit(const ma_loshelf2_config* pConfig, ma_loshelf2* pFilter);
fn C.ma_loshelf2_reinit(p_config &C.ma_loshelf2_config, p_filter &C.ma_loshelf2) Result

// MA_API ma_result ma_loshelf2_process_pcm_frames(ma_loshelf2* pFilter, void* pFramesOut, const void* pFramesIn, ma_uint64 frameCount);
fn C.ma_loshelf2_process_pcm_frames(p_filter &C.ma_loshelf2, p_frames_out voidptr, p_frames_in voidptr, frame_count u64) Result

// MA_API ma_uint32 ma_loshelf2_get_latency(const ma_loshelf2* pFilter);
fn C.ma_loshelf2_get_latency(p_filter &C.ma_loshelf2) u32

// MA_API ma_hishelf2_config ma_hishelf2_config_init(ma_format format, ma_uint32 channels, ma_uint32 sampleRate, double gainDB, double shelfSlope, double frequency);
fn C.ma_hishelf2_config_init(format Format, channels u32, sample_rate u32, gain_d_b f64, shelf_slope f64, frequency f64) C.ma_hishelf2_config

// MA_API ma_result ma_hishelf2_init(const ma_hishelf2_config* pConfig, ma_hishelf2* pFilter);
fn C.ma_hishelf2_init(p_config &C.ma_hishelf2_config, p_filter &C.ma_hishelf2) Result

// MA_API ma_result ma_hishelf2_reinit(const ma_hishelf2_config* pConfig, ma_hishelf2* pFilter);
fn C.ma_hishelf2_reinit(p_config &C.ma_hishelf2_config, p_filter &C.ma_hishelf2) Result

// MA_API ma_result ma_hishelf2_process_pcm_frames(ma_hishelf2* pFilter, void* pFramesOut, const void* pFramesIn, ma_uint64 frameCount);
fn C.ma_hishelf2_process_pcm_frames(p_filter &C.ma_hishelf2, p_frames_out voidptr, p_frames_in voidptr, frame_count u64) Result

// MA_API ma_uint32 ma_hishelf2_get_latency(const ma_hishelf2* pFilter);
fn C.ma_hishelf2_get_latency(p_filter &C.ma_hishelf2) u32

// MA_API ma_linear_resampler_config ma_linear_resampler_config_init(ma_format format, ma_uint32 channels, ma_uint32 sampleRateIn, ma_uint32 sampleRateOut);
fn C.ma_linear_resampler_config_init(format Format, channels u32, sample_rate_in u32, sample_rate_out u32) C.ma_linear_resampler_config

// MA_API ma_result ma_linear_resampler_init(const ma_linear_resampler_config* pConfig, ma_linear_resampler* pResampler);
fn C.ma_linear_resampler_init(p_config &C.ma_linear_resampler_config, p_resampler &C.ma_linear_resampler) Result

// MA_API void ma_linear_resampler_uninit(ma_linear_resampler* pResampler);
fn C.ma_linear_resampler_uninit(p_resampler &C.ma_linear_resampler)

// MA_API ma_result ma_linear_resampler_process_pcm_frames(ma_linear_resampler* pResampler, const void* pFramesIn, ma_uint64* pFrameCountIn, void* pFramesOut, ma_uint64* pFrameCountOut);
fn C.ma_linear_resampler_process_pcm_frames(p_resampler &C.ma_linear_resampler, p_frames_in voidptr, p_frame_count_in &u64, p_frames_out voidptr, p_frame_count_out &u64) Result

// MA_API ma_result ma_linear_resampler_set_rate(ma_linear_resampler* pResampler, ma_uint32 sampleRateIn, ma_uint32 sampleRateOut);
fn C.ma_linear_resampler_set_rate(p_resampler &C.ma_linear_resampler, sample_rate_in u32, sample_rate_out u32) Result

// MA_API ma_result ma_linear_resampler_set_rate_ratio(ma_linear_resampler* pResampler, float ratioInOut);
fn C.ma_linear_resampler_set_rate_ratio(p_resampler &C.ma_linear_resampler, ratio_in_out f32) Result

// MA_API ma_uint64 ma_linear_resampler_get_required_input_frame_count(const ma_linear_resampler* pResampler, ma_uint64 outputFrameCount);
fn C.ma_linear_resampler_get_required_input_frame_count(p_resampler &C.ma_linear_resampler, output_frame_count u64) u64

// MA_API ma_uint64 ma_linear_resampler_get_expected_output_frame_count(const ma_linear_resampler* pResampler, ma_uint64 inputFrameCount);
fn C.ma_linear_resampler_get_expected_output_frame_count(p_resampler &C.ma_linear_resampler, input_frame_count u64) u64

// MA_API ma_uint64 ma_linear_resampler_get_input_latency(const ma_linear_resampler* pResampler);
fn C.ma_linear_resampler_get_input_latency(p_resampler &C.ma_linear_resampler) u64

// MA_API ma_uint64 ma_linear_resampler_get_output_latency(const ma_linear_resampler* pResampler);
fn C.ma_linear_resampler_get_output_latency(p_resampler &C.ma_linear_resampler) u64

// MA_API ma_resampler_config ma_resampler_config_init(ma_format format, ma_uint32 channels, ma_uint32 sampleRateIn, ma_uint32 sampleRateOut, ma_resample_algorithm algorithm);
fn C.ma_resampler_config_init(format Format, channels u32, sample_rate_in u32, sample_rate_out u32, algorithm C.ma_resample_algorithm) C.ma_resampler_config

// MA_API ma_result ma_resampler_init(const ma_resampler_config* pConfig, ma_resampler* pResampler);
fn C.ma_resampler_init(p_config &C.ma_resampler_config, p_resampler &C.ma_resampler) Result

// MA_API void ma_resampler_uninit(ma_resampler* pResampler);
fn C.ma_resampler_uninit(p_resampler &C.ma_resampler)

// MA_API ma_result ma_resampler_process_pcm_frames(ma_resampler* pResampler, const void* pFramesIn, ma_uint64* pFrameCountIn, void* pFramesOut, ma_uint64* pFrameCountOut);
fn C.ma_resampler_process_pcm_frames(p_resampler &C.ma_resampler, p_frames_in voidptr, p_frame_count_in &u64, p_frames_out voidptr, p_frame_count_out &u64) Result

// MA_API ma_result ma_resampler_set_rate(ma_resampler* pResampler, ma_uint32 sampleRateIn, ma_uint32 sampleRateOut);
fn C.ma_resampler_set_rate(p_resampler &C.ma_resampler, sample_rate_in u32, sample_rate_out u32) Result

// MA_API ma_result ma_resampler_set_rate_ratio(ma_resampler* pResampler, float ratio);
fn C.ma_resampler_set_rate_ratio(p_resampler &C.ma_resampler, ratio f32) Result

// MA_API ma_uint64 ma_resampler_get_required_input_frame_count(const ma_resampler* pResampler, ma_uint64 outputFrameCount);
fn C.ma_resampler_get_required_input_frame_count(p_resampler &C.ma_resampler, output_frame_count u64) u64

// MA_API ma_uint64 ma_resampler_get_expected_output_frame_count(const ma_resampler* pResampler, ma_uint64 inputFrameCount);
fn C.ma_resampler_get_expected_output_frame_count(p_resampler &C.ma_resampler, input_frame_count u64) u64

// MA_API ma_uint64 ma_resampler_get_input_latency(const ma_resampler* pResampler);
fn C.ma_resampler_get_input_latency(p_resampler &C.ma_resampler) u64

// MA_API ma_uint64 ma_resampler_get_output_latency(const ma_resampler* pResampler);
fn C.ma_resampler_get_output_latency(p_resampler &C.ma_resampler) u64

// MA_API ma_channel_converter_config ma_channel_converter_config_init(ma_format format, ma_uint32 channelsIn, const ma_channel* pChannelMapIn, ma_uint32 channelsOut, const ma_channel* pChannelMapOut, ma_channel_mix_mode mixingMode);
fn C.ma_channel_converter_config_init(format Format, channels_in u32, p_channel_map_in &C.ma_channel, channels_out u32, p_channel_map_out &C.ma_channel, mixing_mode C.ma_channel_mix_mode) C.ma_channel_converter_config

// MA_API ma_result ma_channel_converter_init(const ma_channel_converter_config* pConfig, ma_channel_converter* pConverter);
fn C.ma_channel_converter_init(p_config &C.ma_channel_converter_config, p_converter &C.ma_channel_converter) Result

// MA_API void ma_channel_converter_uninit(ma_channel_converter* pConverter);
fn C.ma_channel_converter_uninit(p_converter &C.ma_channel_converter)

// MA_API ma_result ma_channel_converter_process_pcm_frames(ma_channel_converter* pConverter, void* pFramesOut, const void* pFramesIn, ma_uint64 frameCount);
fn C.ma_channel_converter_process_pcm_frames(p_converter &C.ma_channel_converter, p_frames_out voidptr, p_frames_in voidptr, frame_count u64) Result

// MA_API ma_data_converter_config ma_data_converter_config_init_default();
fn C.ma_data_converter_config_init_default() C.ma_data_converter_config

// MA_API ma_data_converter_config ma_data_converter_config_init(ma_format formatIn, ma_format formatOut, ma_uint32 channelsIn, ma_uint32 channelsOut, ma_uint32 sampleRateIn, ma_uint32 sampleRateOut);
fn C.ma_data_converter_config_init(format_in Format, format_out Format, channels_in u32, channels_out u32, sample_rate_in u32, sample_rate_out u32) C.ma_data_converter_config

// MA_API ma_result ma_data_converter_init(const ma_data_converter_config* pConfig, ma_data_converter* pConverter);
fn C.ma_data_converter_init(p_config &C.ma_data_converter_config, p_converter &C.ma_data_converter) Result

// MA_API void ma_data_converter_uninit(ma_data_converter* pConverter);
fn C.ma_data_converter_uninit(p_converter &C.ma_data_converter)

// MA_API ma_result ma_data_converter_process_pcm_frames(ma_data_converter* pConverter, const void* pFramesIn, ma_uint64* pFrameCountIn, void* pFramesOut, ma_uint64* pFrameCountOut);
fn C.ma_data_converter_process_pcm_frames(p_converter &C.ma_data_converter, p_frames_in voidptr, p_frame_count_in &u64, p_frames_out voidptr, p_frame_count_out &u64) Result

// MA_API ma_result ma_data_converter_set_rate(ma_data_converter* pConverter, ma_uint32 sampleRateIn, ma_uint32 sampleRateOut);
fn C.ma_data_converter_set_rate(p_converter &C.ma_data_converter, sample_rate_in u32, sample_rate_out u32) Result

// MA_API ma_result ma_data_converter_set_rate_ratio(ma_data_converter* pConverter, float ratioInOut);
fn C.ma_data_converter_set_rate_ratio(p_converter &C.ma_data_converter, ratio_in_out f32) Result

// MA_API ma_uint64 ma_data_converter_get_required_input_frame_count(const ma_data_converter* pConverter, ma_uint64 outputFrameCount);
fn C.ma_data_converter_get_required_input_frame_count(p_converter &C.ma_data_converter, output_frame_count u64) u64

// MA_API ma_uint64 ma_data_converter_get_expected_output_frame_count(const ma_data_converter* pConverter, ma_uint64 inputFrameCount);
fn C.ma_data_converter_get_expected_output_frame_count(p_converter &C.ma_data_converter, input_frame_count u64) u64

// MA_API ma_uint64 ma_data_converter_get_input_latency(const ma_data_converter* pConverter);
fn C.ma_data_converter_get_input_latency(p_converter &C.ma_data_converter) u64

// MA_API ma_uint64 ma_data_converter_get_output_latency(const ma_data_converter* pConverter);
fn C.ma_data_converter_get_output_latency(p_converter &C.ma_data_converter) u64

// MA_API void ma_pcm_u8_to_s16(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_u8_to_s16(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_u8_to_s24(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_u8_to_s24(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_u8_to_s32(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_u8_to_s32(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_u8_to_f32(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_u8_to_f32(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_s16_to_u8(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_s16_to_u8(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_s16_to_s24(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_s16_to_s24(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_s16_to_s32(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_s16_to_s32(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_s16_to_f32(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_s16_to_f32(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_s24_to_u8(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_s24_to_u8(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_s24_to_s16(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_s24_to_s16(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_s24_to_s32(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_s24_to_s32(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_s24_to_f32(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_s24_to_f32(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_s32_to_u8(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_s32_to_u8(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_s32_to_s16(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_s32_to_s16(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_s32_to_s24(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_s32_to_s24(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_s32_to_f32(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_s32_to_f32(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_f32_to_u8(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_f32_to_u8(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_f32_to_s16(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_f32_to_s16(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_f32_to_s24(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_f32_to_s24(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_f32_to_s32(void* pOut, const void* pIn, ma_uint64 count, ma_dither_mode ditherMode);
fn C.ma_pcm_f32_to_s32(p_out voidptr, p_in voidptr, count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_pcm_convert(void* pOut, ma_format formatOut, const void* pIn, ma_format formatIn, ma_uint64 sampleCount, ma_dither_mode ditherMode);
fn C.ma_pcm_convert(p_out voidptr, format_out Format, p_in voidptr, format_in Format, sample_count u64, dither_mode C.ma_dither_mode)

// MA_API void ma_convert_pcm_frames_format(void* pOut, ma_format formatOut, const void* pIn, ma_format formatIn, ma_uint64 frameCount, ma_uint32 channels, ma_dither_mode ditherMode);
fn C.ma_convert_pcm_frames_format(p_out voidptr, format_out Format, p_in voidptr, format_in Format, frame_count u64, channels u32, dither_mode C.ma_dither_mode)

// MA_API void ma_deinterleave_pcm_frames(ma_format format, ma_uint32 channels, ma_uint64 frameCount, const void* pInterleavedPCMFrames, void** ppDeinterleavedPCMFrames);
fn C.ma_deinterleave_pcm_frames(format Format, channels u32, frame_count u64, p_interleaved_p_c_m_frames voidptr, pp_deinterleaved_p_c_m_frames &voidptr)

// MA_API void ma_interleave_pcm_frames(ma_format format, ma_uint32 channels, ma_uint64 frameCount, const void** ppDeinterleavedPCMFrames, void* pInterleavedPCMFrames);
fn C.ma_interleave_pcm_frames(format Format, channels u32, frame_count u64, pp_deinterleaved_p_c_m_frames &voidptr, p_interleaved_p_c_m_frames voidptr)

// MA_API ma_channel ma_channel_map_get_default_channel(ma_uint32 channelCount, ma_uint32 channelIndex);
fn C.ma_channel_map_get_default_channel(channel_count u32, channel_index u32) C.ma_channel

// MA_API ma_channel ma_channel_map_get_channel(const ma_channel* pChannelMap, ma_uint32 channelCount, ma_uint32 channelIndex);
fn C.ma_channel_map_get_channel(p_channel_map &C.ma_channel, channel_count u32, channel_index u32) C.ma_channel

// MA_API void ma_channel_map_init_blank(ma_uint32 channels, ma_channel* pChannelMap);
fn C.ma_channel_map_init_blank(channels u32, p_channel_map &C.ma_channel)

// MA_API void ma_get_standard_channel_map(ma_standard_channel_map standardChannelMap, ma_uint32 channels, ma_channel* pChannelMap);
fn C.ma_get_standard_channel_map(standard_channel_map C.ma_standard_channel_map, channels u32, p_channel_map &C.ma_channel)

// MA_API void ma_channel_map_copy(ma_channel* pOut, const ma_channel* pIn, ma_uint32 channels);
fn C.ma_channel_map_copy(p_out &C.ma_channel, p_in &C.ma_channel, channels u32)

// MA_API void ma_channel_map_copy_or_default(ma_channel* pOut, const ma_channel* pIn, ma_uint32 channels);
fn C.ma_channel_map_copy_or_default(p_out &C.ma_channel, p_in &C.ma_channel, channels u32)

// MA_API ma_bool32 ma_channel_map_valid(ma_uint32 channels, const ma_channel* pChannelMap);
fn C.ma_channel_map_valid(channels u32, p_channel_map &C.ma_channel) bool

// MA_API ma_bool32 ma_channel_map_equal(ma_uint32 channels, const ma_channel* pChannelMapA, const ma_channel* pChannelMapB);
fn C.ma_channel_map_equal(channels u32, p_channel_map_a &C.ma_channel, p_channel_map_b &C.ma_channel) bool

// MA_API ma_bool32 ma_channel_map_blank(ma_uint32 channels, const ma_channel* pChannelMap);
fn C.ma_channel_map_blank(channels u32, p_channel_map &C.ma_channel) bool

// MA_API ma_bool32 ma_channel_map_contains_channel_position(ma_uint32 channels, const ma_channel* pChannelMap, ma_channel channelPosition);
fn C.ma_channel_map_contains_channel_position(channels u32, p_channel_map &C.ma_channel, channel_position C.ma_channel) bool

// MA_API ma_uint64 ma_convert_frames(void* pOut, ma_uint64 frameCountOut, ma_format formatOut, ma_uint32 channelsOut, ma_uint32 sampleRateOut, const void* pIn, ma_uint64 frameCountIn, ma_format formatIn, ma_uint32 channelsIn, ma_uint32 sampleRateIn);
fn C.ma_convert_frames(p_out voidptr, frame_count_out u64, format_out Format, channels_out u32, sample_rate_out u32, p_in voidptr, frame_count_in u64, format_in Format, channels_in u32, sample_rate_in u32) u64

// MA_API ma_uint64 ma_convert_frames_ex(void* pOut, ma_uint64 frameCountOut, const void* pIn, ma_uint64 frameCountIn, const ma_data_converter_config* pConfig);
fn C.ma_convert_frames_ex(p_out voidptr, frame_count_out u64, p_in voidptr, frame_count_in u64, p_config &C.ma_data_converter_config) u64

// MA_API ma_result ma_rb_init_ex(size_t subbufferSizeInBytes, size_t subbufferCount, size_t subbufferStrideInBytes, void* pOptionalPreallocatedBuffer, const ma_allocation_callbacks* pAllocationCallbacks, ma_rb* pRB);
fn C.ma_rb_init_ex(subbuffer_size_in_bytes usize, subbuffer_count usize, subbuffer_stride_in_bytes usize, p_optional_preallocated_buffer voidptr, p_allocation_callbacks &C.ma_allocation_callbacks, p_r_b &C.ma_rb) Result

// MA_API ma_result ma_rb_init(size_t bufferSizeInBytes, void* pOptionalPreallocatedBuffer, const ma_allocation_callbacks* pAllocationCallbacks, ma_rb* pRB);
fn C.ma_rb_init(buffer_size_in_bytes usize, p_optional_preallocated_buffer voidptr, p_allocation_callbacks &C.ma_allocation_callbacks, p_r_b &C.ma_rb) Result

// MA_API void ma_rb_uninit(ma_rb* pRB);
fn C.ma_rb_uninit(p_r_b &C.ma_rb)

// MA_API void ma_rb_reset(ma_rb* pRB);
fn C.ma_rb_reset(p_r_b &C.ma_rb)

// MA_API ma_result ma_rb_acquire_read(ma_rb* pRB, size_t* pSizeInBytes, void** ppBufferOut);
fn C.ma_rb_acquire_read(p_r_b &C.ma_rb, p_size_in_bytes &usize, pp_buffer_out &voidptr) Result

// MA_API ma_result ma_rb_commit_read(ma_rb* pRB, size_t sizeInBytes, void* pBufferOut);
fn C.ma_rb_commit_read(p_r_b &C.ma_rb, size_in_bytes usize, p_buffer_out voidptr) Result

// MA_API ma_result ma_rb_acquire_write(ma_rb* pRB, size_t* pSizeInBytes, void** ppBufferOut);
fn C.ma_rb_acquire_write(p_r_b &C.ma_rb, p_size_in_bytes &usize, pp_buffer_out &voidptr) Result

// MA_API ma_result ma_rb_commit_write(ma_rb* pRB, size_t sizeInBytes, void* pBufferOut);
fn C.ma_rb_commit_write(p_r_b &C.ma_rb, size_in_bytes usize, p_buffer_out voidptr) Result

// MA_API ma_result ma_rb_seek_read(ma_rb* pRB, size_t offsetInBytes);
fn C.ma_rb_seek_read(p_r_b &C.ma_rb, offset_in_bytes usize) Result

// MA_API ma_result ma_rb_seek_write(ma_rb* pRB, size_t offsetInBytes);
fn C.ma_rb_seek_write(p_r_b &C.ma_rb, offset_in_bytes usize) Result

// MA_API ma_int32 ma_rb_pointer_distance(ma_rb* pRB);    /* Returns the distance between the write pointer and the read pointer. Should never be negative for a correct program. Will return the number of bytes that can be read before the read pointer hits the write pointer. */
fn C.ma_rb_pointer_distance(p_r_b &C.ma_rb) int

// MA_API ma_uint32 ma_rb_available_read(ma_rb* pRB);
fn C.ma_rb_available_read(p_r_b &C.ma_rb) u32

// MA_API ma_uint32 ma_rb_available_write(ma_rb* pRB);
fn C.ma_rb_available_write(p_r_b &C.ma_rb) u32

// MA_API size_t ma_rb_get_subbuffer_size(ma_rb* pRB);
fn C.ma_rb_get_subbuffer_size(p_r_b &C.ma_rb) usize

// MA_API size_t ma_rb_get_subbuffer_stride(ma_rb* pRB);
fn C.ma_rb_get_subbuffer_stride(p_r_b &C.ma_rb) usize

// MA_API size_t ma_rb_get_subbuffer_offset(ma_rb* pRB, size_t subbufferIndex);
fn C.ma_rb_get_subbuffer_offset(p_r_b &C.ma_rb, subbuffer_index usize) usize

// MA_API void* ma_rb_get_subbuffer_ptr(ma_rb* pRB, size_t subbufferIndex, void* pBuffer);
fn C.ma_rb_get_subbuffer_ptr(p_r_b &C.ma_rb, subbuffer_index usize, p_buffer voidptr) voidptr

// MA_API ma_result ma_pcm_rb_init_ex(ma_format format, ma_uint32 channels, ma_uint32 subbufferSizeInFrames, ma_uint32 subbufferCount, ma_uint32 subbufferStrideInFrames, void* pOptionalPreallocatedBuffer, const ma_allocation_callbacks* pAllocationCallbacks, ma_pcm_rb* pRB);
fn C.ma_pcm_rb_init_ex(format Format, channels u32, subbuffer_size_in_frames u32, subbuffer_count u32, subbuffer_stride_in_frames u32, p_optional_preallocated_buffer voidptr, p_allocation_callbacks &C.ma_allocation_callbacks, p_r_b &C.ma_pcm_rb) Result

// MA_API ma_result ma_pcm_rb_init(ma_format format, ma_uint32 channels, ma_uint32 bufferSizeInFrames, void* pOptionalPreallocatedBuffer, const ma_allocation_callbacks* pAllocationCallbacks, ma_pcm_rb* pRB);
fn C.ma_pcm_rb_init(format Format, channels u32, buffer_size_in_frames u32, p_optional_preallocated_buffer voidptr, p_allocation_callbacks &C.ma_allocation_callbacks, p_r_b &C.ma_pcm_rb) Result

// MA_API void ma_pcm_rb_uninit(ma_pcm_rb* pRB);
fn C.ma_pcm_rb_uninit(p_r_b &C.ma_pcm_rb)

// MA_API void ma_pcm_rb_reset(ma_pcm_rb* pRB);
fn C.ma_pcm_rb_reset(p_r_b &C.ma_pcm_rb)

// MA_API ma_result ma_pcm_rb_acquire_read(ma_pcm_rb* pRB, ma_uint32* pSizeInFrames, void** ppBufferOut);
fn C.ma_pcm_rb_acquire_read(p_r_b &C.ma_pcm_rb, p_size_in_frames &u32, pp_buffer_out &voidptr) Result

// MA_API ma_result ma_pcm_rb_commit_read(ma_pcm_rb* pRB, ma_uint32 sizeInFrames, void* pBufferOut);
fn C.ma_pcm_rb_commit_read(p_r_b &C.ma_pcm_rb, size_in_frames u32, p_buffer_out voidptr) Result

// MA_API ma_result ma_pcm_rb_acquire_write(ma_pcm_rb* pRB, ma_uint32* pSizeInFrames, void** ppBufferOut);
fn C.ma_pcm_rb_acquire_write(p_r_b &C.ma_pcm_rb, p_size_in_frames &u32, pp_buffer_out &voidptr) Result

// MA_API ma_result ma_pcm_rb_commit_write(ma_pcm_rb* pRB, ma_uint32 sizeInFrames, void* pBufferOut);
fn C.ma_pcm_rb_commit_write(p_r_b &C.ma_pcm_rb, size_in_frames u32, p_buffer_out voidptr) Result

// MA_API ma_result ma_pcm_rb_seek_read(ma_pcm_rb* pRB, ma_uint32 offsetInFrames);
fn C.ma_pcm_rb_seek_read(p_r_b &C.ma_pcm_rb, offset_in_frames u32) Result

// MA_API ma_result ma_pcm_rb_seek_write(ma_pcm_rb* pRB, ma_uint32 offsetInFrames);
fn C.ma_pcm_rb_seek_write(p_r_b &C.ma_pcm_rb, offset_in_frames u32) Result

// MA_API ma_int32 ma_pcm_rb_pointer_distance(ma_pcm_rb* pRB); /* Return value is in frames. */
fn C.ma_pcm_rb_pointer_distance(p_r_b &C.ma_pcm_rb) int

// MA_API ma_uint32 ma_pcm_rb_available_read(ma_pcm_rb* pRB);
fn C.ma_pcm_rb_available_read(p_r_b &C.ma_pcm_rb) u32

// MA_API ma_uint32 ma_pcm_rb_available_write(ma_pcm_rb* pRB);
fn C.ma_pcm_rb_available_write(p_r_b &C.ma_pcm_rb) u32

// MA_API ma_uint32 ma_pcm_rb_get_subbuffer_size(ma_pcm_rb* pRB);
fn C.ma_pcm_rb_get_subbuffer_size(p_r_b &C.ma_pcm_rb) u32

// MA_API ma_uint32 ma_pcm_rb_get_subbuffer_stride(ma_pcm_rb* pRB);
fn C.ma_pcm_rb_get_subbuffer_stride(p_r_b &C.ma_pcm_rb) u32

// MA_API ma_uint32 ma_pcm_rb_get_subbuffer_offset(ma_pcm_rb* pRB, ma_uint32 subbufferIndex);
fn C.ma_pcm_rb_get_subbuffer_offset(p_r_b &C.ma_pcm_rb, subbuffer_index u32) u32

// MA_API void* ma_pcm_rb_get_subbuffer_ptr(ma_pcm_rb* pRB, ma_uint32 subbufferIndex, void* pBuffer);
fn C.ma_pcm_rb_get_subbuffer_ptr(p_r_b &C.ma_pcm_rb, subbuffer_index u32, p_buffer voidptr) voidptr

// MA_API ma_result ma_duplex_rb_init(ma_format captureFormat, ma_uint32 captureChannels, ma_uint32 sampleRate, ma_uint32 captureInternalSampleRate, ma_uint32 captureInternalPeriodSizeInFrames, const ma_allocation_callbacks* pAllocationCallbacks, ma_duplex_rb* pRB);
fn C.ma_duplex_rb_init(capture_format Format, capture_channels u32, sample_rate u32, capture_internal_sample_rate u32, capture_internal_period_size_in_frames u32, p_allocation_callbacks &C.ma_allocation_callbacks, p_r_b &C.ma_duplex_rb) Result

// MA_API ma_result ma_duplex_rb_uninit(ma_duplex_rb* pRB);
fn C.ma_duplex_rb_uninit(p_r_b &C.ma_duplex_rb) Result

// MA_API const char* ma_result_description(ma_result result);
fn C.ma_result_description(result C.ma_result) &char

// MA_API void* ma_malloc(size_t sz, const ma_allocation_callbacks* pAllocationCallbacks);
fn C.ma_malloc(sz usize, p_allocation_callbacks &C.ma_allocation_callbacks) voidptr

// MA_API void* ma_realloc(void* p, size_t sz, const ma_allocation_callbacks* pAllocationCallbacks);
fn C.ma_realloc(p voidptr, sz usize, p_allocation_callbacks &C.ma_allocation_callbacks) voidptr

// MA_API void ma_free(void* p, const ma_allocation_callbacks* pAllocationCallbacks);
fn C.ma_free(p voidptr, p_allocation_callbacks &C.ma_allocation_callbacks)

// MA_API void* ma_aligned_malloc(size_t sz, size_t alignment, const ma_allocation_callbacks* pAllocationCallbacks);
fn C.ma_aligned_malloc(sz usize, alignment usize, p_allocation_callbacks &C.ma_allocation_callbacks) voidptr

// MA_API void ma_aligned_free(void* p, const ma_allocation_callbacks* pAllocationCallbacks);
fn C.ma_aligned_free(p voidptr, p_allocation_callbacks &C.ma_allocation_callbacks)

// MA_API const char* ma_get_format_name(ma_format format);
fn C.ma_get_format_name(format Format) &char

// MA_API void ma_blend_f32(float* pOut, float* pInA, float* pInB, float factor, ma_uint32 channels);
fn C.ma_blend_f32(p_out &f32, p_in_a &f32, p_in_b &f32, factor f32, channels u32)

// MA_API ma_uint32 ma_get_bytes_per_sample(ma_format format);
fn C.ma_get_bytes_per_sample(format Format) u32

// MA_API const char* ma_log_level_to_string(ma_uint32 logLevel);
fn C.ma_log_level_to_string(log_level u32) &char

// MA_API ma_context_config ma_context_config_init();
fn C.ma_context_config_init() C.ma_context_config

// MA_API ma_result ma_context_init(const ma_backend backends[], ma_uint32 backendCount, const ma_context_config* pConfig, ma_context* pContext);
fn C.ma_context_init(backends []C.ma_backend, backend_count u32, p_config &C.ma_context_config, p_context &C.ma_context) Result

// MA_API ma_result ma_context_uninit(ma_context* pContext);
fn C.ma_context_uninit(p_context &C.ma_context) Result

// MA_API size_t ma_context_sizeof();
fn C.ma_context_sizeof() usize

// MA_API ma_log* ma_context_get_log(ma_context* pContext);
fn C.ma_context_get_log(p_context &C.ma_context) &C.ma_log

// MA_API ma_result ma_context_enumerate_devices(ma_context* pContext, ma_enum_devices_callback_proc callback, void* pUserData);
fn C.ma_context_enumerate_devices(p_context &C.ma_context, callback C.ma_enum_devices_callback_proc, p_user_data voidptr) Result

// MA_API ma_result ma_context_get_devices(ma_context* pContext, ma_device_info** ppPlaybackDeviceInfos, ma_uint32* pPlaybackDeviceCount, ma_device_info** ppCaptureDeviceInfos, ma_uint32* pCaptureDeviceCount);
fn C.ma_context_get_devices(p_context &C.ma_context, pp_playback_device_infos &&C.ma_device_info, p_playback_device_count &u32, pp_capture_device_infos &&C.ma_device_info, p_capture_device_count &u32) Result

// MA_API ma_result ma_context_get_device_info(ma_context* pContext, ma_device_type deviceType, const ma_device_id* pDeviceID, ma_share_mode shareMode, ma_device_info* pDeviceInfo);
fn C.ma_context_get_device_info(p_context &C.ma_context, device_type DeviceType, p_device_i_d &C.ma_device_id, share_mode C.ma_share_mode, p_device_info &C.ma_device_info) Result

// MA_API ma_bool32 ma_context_is_loopback_supported(ma_context* pContext);
fn C.ma_context_is_loopback_supported(p_context &C.ma_context) bool

// MA_API ma_device_config ma_device_config_init(ma_device_type deviceType);
fn C.ma_device_config_init(device_type DeviceType) C.ma_device_config

// MA_API ma_result ma_device_init(ma_context* pContext, const ma_device_config* pConfig, ma_device* pDevice);
fn C.ma_device_init(p_context &C.ma_context, p_config &C.ma_device_config, p_device &C.ma_device) Result

// MA_API ma_result ma_device_init_ex(const ma_backend backends[], ma_uint32 backendCount, const ma_context_config* pContextConfig, const ma_device_config* pConfig, ma_device* pDevice);
fn C.ma_device_init_ex(backends []C.ma_backend, backend_count u32, p_context_config &C.ma_context_config, p_config &C.ma_device_config, p_device &C.ma_device) Result

// MA_API void ma_device_uninit(ma_device* pDevice);
fn C.ma_device_uninit(p_device &C.ma_device)

// MA_API ma_context* ma_device_get_context(ma_device* pDevice);
fn C.ma_device_get_context(p_device &C.ma_device) &C.ma_context

// MA_API ma_log* ma_device_get_log(ma_device* pDevice);
fn C.ma_device_get_log(p_device &C.ma_device) &C.ma_log

// MA_API ma_result ma_device_start(ma_device* pDevice);
fn C.ma_device_start(p_device &C.ma_device) Result

// MA_API ma_result ma_device_stop(ma_device* pDevice);
fn C.ma_device_stop(p_device &C.ma_device) Result

// MA_API ma_bool32 ma_device_is_started(const ma_device* pDevice);
fn C.ma_device_is_started(p_device &C.ma_device) bool

// MA_API ma_uint32 ma_device_get_state(const ma_device* pDevice);
fn C.ma_device_get_state(p_device &C.ma_device) u32

// MA_API ma_result ma_device_set_master_volume(ma_device* pDevice, float volume);
fn C.ma_device_set_master_volume(p_device &C.ma_device, volume f32) Result

// MA_API ma_result ma_device_get_master_volume(ma_device* pDevice, float* pVolume);
fn C.ma_device_get_master_volume(p_device &C.ma_device, p_volume &f32) Result

// MA_API ma_result ma_device_set_master_gain_db(ma_device* pDevice, float gainDB);
fn C.ma_device_set_master_gain_db(p_device &C.ma_device, gain_d_b f32) Result

// MA_API ma_result ma_device_get_master_gain_db(ma_device* pDevice, float* pGainDB);
fn C.ma_device_get_master_gain_db(p_device &C.ma_device, p_gain_d_b &f32) Result

// MA_API ma_result ma_device_handle_backend_data_callback(ma_device* pDevice, void* pOutput, const void* pInput, ma_uint32 frameCount);
fn C.ma_device_handle_backend_data_callback(p_device &C.ma_device, p_output voidptr, p_input voidptr, frame_count u32) Result

// MA_API ma_uint32 ma_calculate_buffer_size_in_frames_from_descriptor(const ma_device_descriptor* pDescriptor, ma_uint32 nativeSampleRate, ma_performance_profile performanceProfile);
fn C.ma_calculate_buffer_size_in_frames_from_descriptor(p_descriptor &C.ma_device_descriptor, native_sample_rate u32, performance_profile C.ma_performance_profile) u32

// MA_API const char* ma_get_backend_name(ma_backend backend);
fn C.ma_get_backend_name(backend C.ma_backend) &char

// MA_API ma_bool32 ma_is_backend_enabled(ma_backend backend);
fn C.ma_is_backend_enabled(backend C.ma_backend) bool

// MA_API ma_result ma_get_enabled_backends(ma_backend* pBackends, size_t backendCap, size_t* pBackendCount);
fn C.ma_get_enabled_backends(p_backends &C.ma_backend, backend_cap usize, p_backend_count &usize) Result

// MA_API ma_bool32 ma_is_loopback_supported(ma_backend backend);
fn C.ma_is_loopback_supported(backend C.ma_backend) bool

// MA_API ma_result ma_spinlock_lock(volatile ma_spinlock* pSpinlock);
fn C.ma_spinlock_lock(p_spinlock &C.ma_spinlock) Result

// MA_API ma_result ma_spinlock_lock_noyield(volatile ma_spinlock* pSpinlock);
fn C.ma_spinlock_lock_noyield(p_spinlock &C.ma_spinlock) Result

// MA_API ma_result ma_spinlock_unlock(volatile ma_spinlock* pSpinlock);
fn C.ma_spinlock_unlock(p_spinlock &C.ma_spinlock) Result

// MA_API ma_result ma_mutex_init(ma_mutex* pMutex);
fn C.ma_mutex_init(p_mutex &C.ma_mutex) Result

// MA_API void ma_mutex_uninit(ma_mutex* pMutex);
fn C.ma_mutex_uninit(p_mutex &C.ma_mutex)

// MA_API void ma_mutex_lock(ma_mutex* pMutex);
fn C.ma_mutex_lock(p_mutex &C.ma_mutex)

// MA_API void ma_mutex_unlock(ma_mutex* pMutex);
fn C.ma_mutex_unlock(p_mutex &C.ma_mutex)

// MA_API ma_result ma_event_init(ma_event* pEvent);
fn C.ma_event_init(p_event &C.ma_event) Result

// MA_API void ma_event_uninit(ma_event* pEvent);
fn C.ma_event_uninit(p_event &C.ma_event)

// MA_API ma_result ma_event_wait(ma_event* pEvent);
fn C.ma_event_wait(p_event &C.ma_event) Result

// MA_API ma_result ma_event_signal(ma_event* pEvent);
fn C.ma_event_signal(p_event &C.ma_event) Result

// MA_API ma_uint32 ma_scale_buffer_size(ma_uint32 baseBufferSize, float scale);
fn C.ma_scale_buffer_size(base_buffer_size u32, scale f32) u32

// MA_API ma_uint32 ma_calculate_buffer_size_in_milliseconds_from_frames(ma_uint32 bufferSizeInFrames, ma_uint32 sampleRate);
fn C.ma_calculate_buffer_size_in_milliseconds_from_frames(buffer_size_in_frames u32, sample_rate u32) u32

// MA_API ma_uint32 ma_calculate_buffer_size_in_frames_from_milliseconds(ma_uint32 bufferSizeInMilliseconds, ma_uint32 sampleRate);
fn C.ma_calculate_buffer_size_in_frames_from_milliseconds(buffer_size_in_milliseconds u32, sample_rate u32) u32

// MA_API void ma_copy_pcm_frames(void* dst, const void* src, ma_uint64 frameCount, ma_format format, ma_uint32 channels);
fn C.ma_copy_pcm_frames(dst voidptr, src voidptr, frame_count u64, format Format, channels u32)

// MA_API void ma_silence_pcm_frames(void* p, ma_uint64 frameCount, ma_format format, ma_uint32 channels);
fn C.ma_silence_pcm_frames(p voidptr, frame_count u64, format Format, channels u32)

// MA_API void* ma_offset_pcm_frames_ptr(void* p, ma_uint64 offsetInFrames, ma_format format, ma_uint32 channels);
fn C.ma_offset_pcm_frames_ptr(p voidptr, offset_in_frames u64, format Format, channels u32) voidptr

// MA_API const void* ma_offset_pcm_frames_const_ptr(const void* p, ma_uint64 offsetInFrames, ma_format format, ma_uint32 channels);
fn C.ma_offset_pcm_frames_const_ptr(p voidptr, offset_in_frames u64, format Format, channels u32) voidptr

// MA_API void ma_clip_samples_f32(float* p, ma_uint64 sampleCount);
fn C.ma_clip_samples_f32(p &f32, sample_count u64)

// MA_API void ma_copy_and_apply_volume_factor_u8(ma_uint8* pSamplesOut, const ma_uint8* pSamplesIn, ma_uint64 sampleCount, float factor);
fn C.ma_copy_and_apply_volume_factor_u8(p_samples_out &C.ma_uint8, p_samples_in &C.ma_uint8, sample_count u64, factor f32)

// MA_API void ma_copy_and_apply_volume_factor_s16(ma_int16* pSamplesOut, const ma_int16* pSamplesIn, ma_uint64 sampleCount, float factor);
fn C.ma_copy_and_apply_volume_factor_s16(p_samples_out &C.ma_int16, p_samples_in &C.ma_int16, sample_count u64, factor f32)

// MA_API void ma_copy_and_apply_volume_factor_s24(void* pSamplesOut, const void* pSamplesIn, ma_uint64 sampleCount, float factor);
fn C.ma_copy_and_apply_volume_factor_s24(p_samples_out voidptr, p_samples_in voidptr, sample_count u64, factor f32)

// MA_API void ma_copy_and_apply_volume_factor_s32(ma_int32* pSamplesOut, const ma_int32* pSamplesIn, ma_uint64 sampleCount, float factor);
fn C.ma_copy_and_apply_volume_factor_s32(p_samples_out &int, p_samples_in &int, sample_count u64, factor f32)

// MA_API void ma_copy_and_apply_volume_factor_f32(float* pSamplesOut, const float* pSamplesIn, ma_uint64 sampleCount, float factor);
fn C.ma_copy_and_apply_volume_factor_f32(p_samples_out &f32, p_samples_in &f32, sample_count u64, factor f32)

// MA_API void ma_apply_volume_factor_u8(ma_uint8* pSamples, ma_uint64 sampleCount, float factor);
fn C.ma_apply_volume_factor_u8(p_samples &C.ma_uint8, sample_count u64, factor f32)

// MA_API void ma_apply_volume_factor_s16(ma_int16* pSamples, ma_uint64 sampleCount, float factor);
fn C.ma_apply_volume_factor_s16(p_samples &C.ma_int16, sample_count u64, factor f32)

// MA_API void ma_apply_volume_factor_s24(void* pSamples, ma_uint64 sampleCount, float factor);
fn C.ma_apply_volume_factor_s24(p_samples voidptr, sample_count u64, factor f32)

// MA_API void ma_apply_volume_factor_s32(ma_int32* pSamples, ma_uint64 sampleCount, float factor);
fn C.ma_apply_volume_factor_s32(p_samples &int, sample_count u64, factor f32)

// MA_API void ma_apply_volume_factor_f32(float* pSamples, ma_uint64 sampleCount, float factor);
fn C.ma_apply_volume_factor_f32(p_samples &f32, sample_count u64, factor f32)

// MA_API void ma_copy_and_apply_volume_factor_pcm_frames_u8(ma_uint8* pPCMFramesOut, const ma_uint8* pPCMFramesIn, ma_uint64 frameCount, ma_uint32 channels, float factor);
fn C.ma_copy_and_apply_volume_factor_pcm_frames_u8(p_p_c_m_frames_out &C.ma_uint8, p_p_c_m_frames_in &C.ma_uint8, frame_count u64, channels u32, factor f32)

// MA_API void ma_copy_and_apply_volume_factor_pcm_frames_s16(ma_int16* pPCMFramesOut, const ma_int16* pPCMFramesIn, ma_uint64 frameCount, ma_uint32 channels, float factor);
fn C.ma_copy_and_apply_volume_factor_pcm_frames_s16(p_p_c_m_frames_out &C.ma_int16, p_p_c_m_frames_in &C.ma_int16, frame_count u64, channels u32, factor f32)

// MA_API void ma_copy_and_apply_volume_factor_pcm_frames_s24(void* pPCMFramesOut, const void* pPCMFramesIn, ma_uint64 frameCount, ma_uint32 channels, float factor);
fn C.ma_copy_and_apply_volume_factor_pcm_frames_s24(p_p_c_m_frames_out voidptr, p_p_c_m_frames_in voidptr, frame_count u64, channels u32, factor f32)

// MA_API void ma_copy_and_apply_volume_factor_pcm_frames_s32(ma_int32* pPCMFramesOut, const ma_int32* pPCMFramesIn, ma_uint64 frameCount, ma_uint32 channels, float factor);
fn C.ma_copy_and_apply_volume_factor_pcm_frames_s32(p_p_c_m_frames_out &int, p_p_c_m_frames_in &int, frame_count u64, channels u32, factor f32)

// MA_API void ma_copy_and_apply_volume_factor_pcm_frames_f32(float* pPCMFramesOut, const float* pPCMFramesIn, ma_uint64 frameCount, ma_uint32 channels, float factor);
fn C.ma_copy_and_apply_volume_factor_pcm_frames_f32(p_p_c_m_frames_out &f32, p_p_c_m_frames_in &f32, frame_count u64, channels u32, factor f32)

// MA_API void ma_copy_and_apply_volume_factor_pcm_frames(void* pFramesOut, const void* pFramesIn, ma_uint64 frameCount, ma_format format, ma_uint32 channels, float factor);
fn C.ma_copy_and_apply_volume_factor_pcm_frames(p_frames_out voidptr, p_frames_in voidptr, frame_count u64, format Format, channels u32, factor f32)

// MA_API void ma_apply_volume_factor_pcm_frames_u8(ma_uint8* pFrames, ma_uint64 frameCount, ma_uint32 channels, float factor);
fn C.ma_apply_volume_factor_pcm_frames_u8(p_frames &C.ma_uint8, frame_count u64, channels u32, factor f32)

// MA_API void ma_apply_volume_factor_pcm_frames_s16(ma_int16* pFrames, ma_uint64 frameCount, ma_uint32 channels, float factor);
fn C.ma_apply_volume_factor_pcm_frames_s16(p_frames &C.ma_int16, frame_count u64, channels u32, factor f32)

// MA_API void ma_apply_volume_factor_pcm_frames_s24(void* pFrames, ma_uint64 frameCount, ma_uint32 channels, float factor);
fn C.ma_apply_volume_factor_pcm_frames_s24(p_frames voidptr, frame_count u64, channels u32, factor f32)

// MA_API void ma_apply_volume_factor_pcm_frames_s32(ma_int32* pFrames, ma_uint64 frameCount, ma_uint32 channels, float factor);
fn C.ma_apply_volume_factor_pcm_frames_s32(p_frames &int, frame_count u64, channels u32, factor f32)

// MA_API void ma_apply_volume_factor_pcm_frames_f32(float* pFrames, ma_uint64 frameCount, ma_uint32 channels, float factor);
fn C.ma_apply_volume_factor_pcm_frames_f32(p_frames &f32, frame_count u64, channels u32, factor f32)

// MA_API void ma_apply_volume_factor_pcm_frames(void* pFrames, ma_uint64 frameCount, ma_format format, ma_uint32 channels, float factor);
fn C.ma_apply_volume_factor_pcm_frames(p_frames voidptr, frame_count u64, format Format, channels u32, factor f32)

// MA_API float ma_factor_to_gain_db(float factor);
fn C.ma_factor_to_gain_db(factor f32) f32

// MA_API float ma_gain_db_to_factor(float gain);
fn C.ma_gain_db_to_factor(gain f32) f32

// MA_API ma_data_source_config ma_data_source_config_init();
fn C.ma_data_source_config_init() C.ma_data_source_config

// MA_API ma_result ma_data_source_init(const ma_data_source_config* pConfig, ma_data_source* pDataSource);
fn C.ma_data_source_init(p_config &C.ma_data_source_config, p_data_source &C.ma_data_source) Result

// MA_API void ma_data_source_uninit(ma_data_source* pDataSource);
fn C.ma_data_source_uninit(p_data_source &C.ma_data_source)

// MA_API ma_result ma_data_source_read_pcm_frames(ma_data_source* pDataSource, void* pFramesOut, ma_uint64 frameCount, ma_uint64* pFramesRead, ma_bool32 loop);   /* Must support pFramesOut = NULL in which case a forward seek should be performed. */
fn C.ma_data_source_read_pcm_frames(p_data_source &C.ma_data_source, p_frames_out voidptr, frame_count u64, p_frames_read &u64, loop bool) Result

// MA_API ma_result ma_data_source_seek_pcm_frames(ma_data_source* pDataSource, ma_uint64 frameCount, ma_uint64* pFramesSeeked, ma_bool32 loop); /* Can only seek forward. Equivalent to ma_data_source_read_pcm_frames(pDataSource, NULL, frameCount); */
fn C.ma_data_source_seek_pcm_frames(p_data_source &C.ma_data_source, frame_count u64, p_frames_seeked &u64, loop bool) Result

// MA_API ma_result ma_data_source_seek_to_pcm_frame(ma_data_source* pDataSource, ma_uint64 frameIndex);
fn C.ma_data_source_seek_to_pcm_frame(p_data_source &C.ma_data_source, frame_index u64) Result

// MA_API ma_result ma_data_source_map(ma_data_source* pDataSource, void** ppFramesOut, ma_uint64* pFrameCount);   /* Returns MA_NOT_IMPLEMENTED if mapping is not supported. */
fn C.ma_data_source_map(p_data_source &C.ma_data_source, pp_frames_out &voidptr, p_frame_count &u64) Result

// MA_API ma_result ma_data_source_unmap(ma_data_source* pDataSource, ma_uint64 frameCount);       /* Returns MA_AT_END if the end has been reached. */
fn C.ma_data_source_unmap(p_data_source &C.ma_data_source, frame_count u64) Result

// MA_API ma_result ma_data_source_get_data_format(ma_data_source* pDataSource, ma_format* pFormat, ma_uint32* pChannels, ma_uint32* pSampleRate);
fn C.ma_data_source_get_data_format(p_data_source &C.ma_data_source, p_format &Format, p_channels &u32, p_sample_rate &u32) Result

// MA_API ma_result ma_data_source_get_cursor_in_pcm_frames(ma_data_source* pDataSource, ma_uint64* pCursor);
fn C.ma_data_source_get_cursor_in_pcm_frames(p_data_source &C.ma_data_source, p_cursor &u64) Result

// MA_API ma_result ma_data_source_get_length_in_pcm_frames(ma_data_source* pDataSource, ma_uint64* pLength);    /* Returns MA_NOT_IMPLEMENTED if the length is unknown or cannot be determined. Decoders can return this. */
fn C.ma_data_source_get_length_in_pcm_frames(p_data_source &C.ma_data_source, p_length &u64) Result

// MA_API ma_result ma_data_source_set_range_in_pcm_frames(ma_data_source* pDataSource, ma_uint64 rangeBegInFrames, ma_uint64 rangeEndInFrames);
fn C.ma_data_source_set_range_in_pcm_frames(p_data_source &C.ma_data_source, range_beg_in_frames u64, range_end_in_frames u64) Result

// MA_API void ma_data_source_get_range_in_pcm_frames(ma_data_source* pDataSource, ma_uint64* pRangeBegInFrames, ma_uint64* pRangeEndInFrames);
fn C.ma_data_source_get_range_in_pcm_frames(p_data_source &C.ma_data_source, p_range_beg_in_frames &u64, p_range_end_in_frames &u64)

// MA_API ma_result ma_data_source_set_loop_point_in_pcm_frames(ma_data_source* pDataSource, ma_uint64 loopBegInFrames, ma_uint64 loopEndInFrames);
fn C.ma_data_source_set_loop_point_in_pcm_frames(p_data_source &C.ma_data_source, loop_beg_in_frames u64, loop_end_in_frames u64) Result

// MA_API void ma_data_source_get_loop_point_in_pcm_frames(ma_data_source* pDataSource, ma_uint64* pLoopBegInFrames, ma_uint64* pLoopEndInFrames);
fn C.ma_data_source_get_loop_point_in_pcm_frames(p_data_source &C.ma_data_source, p_loop_beg_in_frames &u64, p_loop_end_in_frames &u64)

// MA_API ma_result ma_data_source_set_current(ma_data_source* pDataSource, ma_data_source* pCurrentDataSource);
fn C.ma_data_source_set_current(p_data_source &C.ma_data_source, p_current_data_source &C.ma_data_source) Result

// MA_API ma_data_source* ma_data_source_get_current(ma_data_source* pDataSource);
fn C.ma_data_source_get_current(p_data_source &C.ma_data_source) &C.ma_data_source

// MA_API ma_result ma_data_source_set_next(ma_data_source* pDataSource, ma_data_source* pNextDataSource);
fn C.ma_data_source_set_next(p_data_source &C.ma_data_source, p_next_data_source &C.ma_data_source) Result

// MA_API ma_data_source* ma_data_source_get_next(ma_data_source* pDataSource);
fn C.ma_data_source_get_next(p_data_source &C.ma_data_source) &C.ma_data_source

// MA_API ma_result ma_data_source_set_next_callback(ma_data_source* pDataSource, ma_data_source_get_next_proc onGetNext);
fn C.ma_data_source_set_next_callback(p_data_source &C.ma_data_source, on_get_next C.ma_data_source_get_next_proc) Result

// MA_API ma_data_source_get_next_proc ma_data_source_get_next_callback(ma_data_source* pDataSource);
fn C.ma_data_source_get_next_callback(p_data_source &C.ma_data_source) C.ma_data_source_get_next_proc

// MA_API ma_result ma_audio_buffer_ref_init(ma_format format, ma_uint32 channels, const void* pData, ma_uint64 sizeInFrames, ma_audio_buffer_ref* pAudioBufferRef);
fn C.ma_audio_buffer_ref_init(format Format, channels u32, p_data voidptr, size_in_frames u64, p_audio_buffer_ref &C.ma_audio_buffer_ref) Result

// MA_API void ma_audio_buffer_ref_uninit(ma_audio_buffer_ref* pAudioBufferRef);
fn C.ma_audio_buffer_ref_uninit(p_audio_buffer_ref &C.ma_audio_buffer_ref)

// MA_API ma_result ma_audio_buffer_ref_set_data(ma_audio_buffer_ref* pAudioBufferRef, const void* pData, ma_uint64 sizeInFrames);
fn C.ma_audio_buffer_ref_set_data(p_audio_buffer_ref &C.ma_audio_buffer_ref, p_data voidptr, size_in_frames u64) Result

// MA_API ma_uint64 ma_audio_buffer_ref_read_pcm_frames(ma_audio_buffer_ref* pAudioBufferRef, void* pFramesOut, ma_uint64 frameCount, ma_bool32 loop);
fn C.ma_audio_buffer_ref_read_pcm_frames(p_audio_buffer_ref &C.ma_audio_buffer_ref, p_frames_out voidptr, frame_count u64, loop bool) u64

// MA_API ma_result ma_audio_buffer_ref_seek_to_pcm_frame(ma_audio_buffer_ref* pAudioBufferRef, ma_uint64 frameIndex);
fn C.ma_audio_buffer_ref_seek_to_pcm_frame(p_audio_buffer_ref &C.ma_audio_buffer_ref, frame_index u64) Result

// MA_API ma_result ma_audio_buffer_ref_map(ma_audio_buffer_ref* pAudioBufferRef, void** ppFramesOut, ma_uint64* pFrameCount);
fn C.ma_audio_buffer_ref_map(p_audio_buffer_ref &C.ma_audio_buffer_ref, pp_frames_out &voidptr, p_frame_count &u64) Result

// MA_API ma_result ma_audio_buffer_ref_unmap(ma_audio_buffer_ref* pAudioBufferRef, ma_uint64 frameCount);    /* Returns MA_AT_END if the end has been reached. This should be considered successful. */
fn C.ma_audio_buffer_ref_unmap(p_audio_buffer_ref &C.ma_audio_buffer_ref, frame_count u64) Result

// MA_API ma_bool32 ma_audio_buffer_ref_at_end(const ma_audio_buffer_ref* pAudioBufferRef);
fn C.ma_audio_buffer_ref_at_end(p_audio_buffer_ref &C.ma_audio_buffer_ref) bool

// MA_API ma_result ma_audio_buffer_ref_get_cursor_in_pcm_frames(const ma_audio_buffer_ref* pAudioBufferRef, ma_uint64* pCursor);
fn C.ma_audio_buffer_ref_get_cursor_in_pcm_frames(p_audio_buffer_ref &C.ma_audio_buffer_ref, p_cursor &u64) Result

// MA_API ma_result ma_audio_buffer_ref_get_length_in_pcm_frames(const ma_audio_buffer_ref* pAudioBufferRef, ma_uint64* pLength);
fn C.ma_audio_buffer_ref_get_length_in_pcm_frames(p_audio_buffer_ref &C.ma_audio_buffer_ref, p_length &u64) Result

// MA_API ma_result ma_audio_buffer_ref_get_available_frames(const ma_audio_buffer_ref* pAudioBufferRef, ma_uint64* pAvailableFrames);
fn C.ma_audio_buffer_ref_get_available_frames(p_audio_buffer_ref &C.ma_audio_buffer_ref, p_available_frames &u64) Result

// MA_API ma_audio_buffer_config ma_audio_buffer_config_init(ma_format format, ma_uint32 channels, ma_uint64 sizeInFrames, const void* pData, const ma_allocation_callbacks* pAllocationCallbacks);
fn C.ma_audio_buffer_config_init(format Format, channels u32, size_in_frames u64, p_data voidptr, p_allocation_callbacks &C.ma_allocation_callbacks) C.ma_audio_buffer_config

// MA_API ma_result ma_audio_buffer_init(const ma_audio_buffer_config* pConfig, ma_audio_buffer* pAudioBuffer);
fn C.ma_audio_buffer_init(p_config &C.ma_audio_buffer_config, p_audio_buffer &C.ma_audio_buffer) Result

// MA_API ma_result ma_audio_buffer_init_copy(const ma_audio_buffer_config* pConfig, ma_audio_buffer* pAudioBuffer);
fn C.ma_audio_buffer_init_copy(p_config &C.ma_audio_buffer_config, p_audio_buffer &C.ma_audio_buffer) Result

// MA_API ma_result ma_audio_buffer_alloc_and_init(const ma_audio_buffer_config* pConfig, ma_audio_buffer** ppAudioBuffer);  /* Always copies the data. Doesn't make sense to use this otherwise. Use ma_audio_buffer_uninit_and_free() to uninit. */
fn C.ma_audio_buffer_alloc_and_init(p_config &C.ma_audio_buffer_config, pp_audio_buffer &&C.ma_audio_buffer) Result

// MA_API void ma_audio_buffer_uninit(ma_audio_buffer* pAudioBuffer);
fn C.ma_audio_buffer_uninit(p_audio_buffer &C.ma_audio_buffer)

// MA_API void ma_audio_buffer_uninit_and_free(ma_audio_buffer* pAudioBuffer);
fn C.ma_audio_buffer_uninit_and_free(p_audio_buffer &C.ma_audio_buffer)

// MA_API ma_uint64 ma_audio_buffer_read_pcm_frames(ma_audio_buffer* pAudioBuffer, void* pFramesOut, ma_uint64 frameCount, ma_bool32 loop);
fn C.ma_audio_buffer_read_pcm_frames(p_audio_buffer &C.ma_audio_buffer, p_frames_out voidptr, frame_count u64, loop bool) u64

// MA_API ma_result ma_audio_buffer_seek_to_pcm_frame(ma_audio_buffer* pAudioBuffer, ma_uint64 frameIndex);
fn C.ma_audio_buffer_seek_to_pcm_frame(p_audio_buffer &C.ma_audio_buffer, frame_index u64) Result

// MA_API ma_result ma_audio_buffer_map(ma_audio_buffer* pAudioBuffer, void** ppFramesOut, ma_uint64* pFrameCount);
fn C.ma_audio_buffer_map(p_audio_buffer &C.ma_audio_buffer, pp_frames_out &voidptr, p_frame_count &u64) Result

// MA_API ma_result ma_audio_buffer_unmap(ma_audio_buffer* pAudioBuffer, ma_uint64 frameCount);    /* Returns MA_AT_END if the end has been reached. This should be considered successful. */
fn C.ma_audio_buffer_unmap(p_audio_buffer &C.ma_audio_buffer, frame_count u64) Result

// MA_API ma_bool32 ma_audio_buffer_at_end(const ma_audio_buffer* pAudioBuffer);
fn C.ma_audio_buffer_at_end(p_audio_buffer &C.ma_audio_buffer) bool

// MA_API ma_result ma_audio_buffer_get_cursor_in_pcm_frames(const ma_audio_buffer* pAudioBuffer, ma_uint64* pCursor);
fn C.ma_audio_buffer_get_cursor_in_pcm_frames(p_audio_buffer &C.ma_audio_buffer, p_cursor &u64) Result

// MA_API ma_result ma_audio_buffer_get_length_in_pcm_frames(const ma_audio_buffer* pAudioBuffer, ma_uint64* pLength);
fn C.ma_audio_buffer_get_length_in_pcm_frames(p_audio_buffer &C.ma_audio_buffer, p_length &u64) Result

// MA_API ma_result ma_audio_buffer_get_available_frames(const ma_audio_buffer* pAudioBuffer, ma_uint64* pAvailableFrames);
fn C.ma_audio_buffer_get_available_frames(p_audio_buffer &C.ma_audio_buffer, p_available_frames &u64) Result

// MA_API ma_result ma_vfs_open(ma_vfs* pVFS, const char* pFilePath, ma_uint32 openMode, ma_vfs_file* pFile);
fn C.ma_vfs_open(p_v_f_s &C.ma_vfs, p_file_path charptr, open_mode u32, p_file &C.ma_vfs_file) Result

// MA_API ma_result ma_vfs_open_w(ma_vfs* pVFS, const wchar_t* pFilePath, ma_uint32 openMode, ma_vfs_file* pFile);
fn C.ma_vfs_open_w(p_v_f_s &C.ma_vfs, p_file_path &C.wchar_t, open_mode u32, p_file &C.ma_vfs_file) Result

// MA_API ma_result ma_vfs_close(ma_vfs* pVFS, ma_vfs_file file);
fn C.ma_vfs_close(p_v_f_s &C.ma_vfs, file C.ma_vfs_file) Result

// MA_API ma_result ma_vfs_read(ma_vfs* pVFS, ma_vfs_file file, void* pDst, size_t sizeInBytes, size_t* pBytesRead);
fn C.ma_vfs_read(p_v_f_s &C.ma_vfs, file C.ma_vfs_file, p_dst voidptr, size_in_bytes usize, p_bytes_read &usize) Result

// MA_API ma_result ma_vfs_write(ma_vfs* pVFS, ma_vfs_file file, const void* pSrc, size_t sizeInBytes, size_t* pBytesWritten);
fn C.ma_vfs_write(p_v_f_s &C.ma_vfs, file C.ma_vfs_file, p_src voidptr, size_in_bytes usize, p_bytes_written &usize) Result

// MA_API ma_result ma_vfs_seek(ma_vfs* pVFS, ma_vfs_file file, ma_int64 offset, ma_seek_origin origin);
fn C.ma_vfs_seek(p_v_f_s &C.ma_vfs, file C.ma_vfs_file, offset C.ma_int64, origin C.ma_seek_origin) Result

// MA_API ma_result ma_vfs_tell(ma_vfs* pVFS, ma_vfs_file file, ma_int64* pCursor);
fn C.ma_vfs_tell(p_v_f_s &C.ma_vfs, file C.ma_vfs_file, p_cursor &C.ma_int64) Result

// MA_API ma_result ma_vfs_info(ma_vfs* pVFS, ma_vfs_file file, ma_file_info* pInfo);
fn C.ma_vfs_info(p_v_f_s &C.ma_vfs, file C.ma_vfs_file, p_info &C.ma_file_info) Result

// MA_API ma_result ma_vfs_open_and_read_file(ma_vfs* pVFS, const char* pFilePath, void** ppData, size_t* pSize, const ma_allocation_callbacks* pAllocationCallbacks);
fn C.ma_vfs_open_and_read_file(p_v_f_s &C.ma_vfs, p_file_path charptr, pp_data &voidptr, p_size &usize, p_allocation_callbacks &C.ma_allocation_callbacks) Result

// MA_API ma_result ma_default_vfs_init(ma_default_vfs* pVFS, const ma_allocation_callbacks* pAllocationCallbacks);
fn C.ma_default_vfs_init(p_v_f_s &C.ma_default_vfs, p_allocation_callbacks &C.ma_allocation_callbacks) Result

// MA_API ma_decoding_backend_config ma_decoding_backend_config_init(ma_format preferredFormat);
fn C.ma_decoding_backend_config_init(preferred_format Format) C.ma_decoding_backend_config

// MA_API ma_decoder_config ma_decoder_config_init(ma_format outputFormat, ma_uint32 outputChannels, ma_uint32 outputSampleRate);
fn C.ma_decoder_config_init(output_format Format, output_channels u32, output_sample_rate u32) C.ma_decoder_config

// MA_API ma_decoder_config ma_decoder_config_init_default();
fn C.ma_decoder_config_init_default() C.ma_decoder_config

// MA_API ma_result ma_decoder_init(ma_decoder_read_proc onRead, ma_decoder_seek_proc onSeek, void* pUserData, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init(on_read C.ma_decoder_read_proc, on_seek C.ma_decoder_seek_proc, p_user_data voidptr, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_memory(const void* pData, size_t dataSize, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_memory(p_data voidptr, data_size usize, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_vfs(ma_vfs* pVFS, const char* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_vfs(p_v_f_s &C.ma_vfs, p_file_path charptr, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_vfs_w(ma_vfs* pVFS, const wchar_t* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_vfs_w(p_v_f_s &C.ma_vfs, p_file_path &C.wchar_t, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_file(const char* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_file(p_file_path charptr, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_file_w(const wchar_t* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_file_w(p_file_path &C.wchar_t, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_uninit(ma_decoder* pDecoder);
fn C.ma_decoder_uninit(p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_get_cursor_in_pcm_frames(ma_decoder* pDecoder, ma_uint64* pCursor);
fn C.ma_decoder_get_cursor_in_pcm_frames(p_decoder &C.ma_decoder, p_cursor &u64) Result

// MA_API ma_uint64 ma_decoder_get_length_in_pcm_frames(ma_decoder* pDecoder);
fn C.ma_decoder_get_length_in_pcm_frames(p_decoder &C.ma_decoder) u64

// MA_API ma_uint64 ma_decoder_read_pcm_frames(ma_decoder* pDecoder, void* pFramesOut, ma_uint64 frameCount);
fn C.ma_decoder_read_pcm_frames(p_decoder &C.ma_decoder, p_frames_out voidptr, frame_count u64) u64

// MA_API ma_result ma_decoder_seek_to_pcm_frame(ma_decoder* pDecoder, ma_uint64 frameIndex);
fn C.ma_decoder_seek_to_pcm_frame(p_decoder &C.ma_decoder, frame_index u64) Result

// MA_API ma_result ma_decoder_get_available_frames(ma_decoder* pDecoder, ma_uint64* pAvailableFrames);
fn C.ma_decoder_get_available_frames(p_decoder &C.ma_decoder, p_available_frames &u64) Result

// MA_API ma_result ma_decode_from_vfs(ma_vfs* pVFS, const char* pFilePath, ma_decoder_config* pConfig, ma_uint64* pFrameCountOut, void** ppPCMFramesOut);
fn C.ma_decode_from_vfs(p_v_f_s &C.ma_vfs, p_file_path charptr, p_config &C.ma_decoder_config, p_frame_count_out &u64, pp_p_c_m_frames_out &voidptr) Result

// MA_API ma_result ma_decode_file(const char* pFilePath, ma_decoder_config* pConfig, ma_uint64* pFrameCountOut, void** ppPCMFramesOut);
fn C.ma_decode_file(p_file_path charptr, p_config &C.ma_decoder_config, p_frame_count_out &u64, pp_p_c_m_frames_out &voidptr) Result

// MA_API ma_result ma_decode_memory(const void* pData, size_t dataSize, ma_decoder_config* pConfig, ma_uint64* pFrameCountOut, void** ppPCMFramesOut);
fn C.ma_decode_memory(p_data voidptr, data_size usize, p_config &C.ma_decoder_config, p_frame_count_out &u64, pp_p_c_m_frames_out &voidptr) Result

// MA_API ma_result ma_decoder_init_wav(ma_decoder_read_proc onRead, ma_decoder_seek_proc onSeek, void* pUserData, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_wav(on_read C.ma_decoder_read_proc, on_seek C.ma_decoder_seek_proc, p_user_data voidptr, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_flac(ma_decoder_read_proc onRead, ma_decoder_seek_proc onSeek, void* pUserData, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_flac(on_read C.ma_decoder_read_proc, on_seek C.ma_decoder_seek_proc, p_user_data voidptr, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_mp3(ma_decoder_read_proc onRead, ma_decoder_seek_proc onSeek, void* pUserData, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_mp3(on_read C.ma_decoder_read_proc, on_seek C.ma_decoder_seek_proc, p_user_data voidptr, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_vorbis(ma_decoder_read_proc onRead, ma_decoder_seek_proc onSeek, void* pUserData, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_vorbis(on_read C.ma_decoder_read_proc, on_seek C.ma_decoder_seek_proc, p_user_data voidptr, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_memory_wav(const void* pData, size_t dataSize, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_memory_wav(p_data voidptr, data_size usize, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_memory_flac(const void* pData, size_t dataSize, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_memory_flac(p_data voidptr, data_size usize, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_memory_mp3(const void* pData, size_t dataSize, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_memory_mp3(p_data voidptr, data_size usize, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_memory_vorbis(const void* pData, size_t dataSize, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_memory_vorbis(p_data voidptr, data_size usize, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_vfs_wav(ma_vfs* pVFS, const char* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_vfs_wav(p_v_f_s &C.ma_vfs, p_file_path charptr, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_vfs_flac(ma_vfs* pVFS, const char* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_vfs_flac(p_v_f_s &C.ma_vfs, p_file_path charptr, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_vfs_mp3(ma_vfs* pVFS, const char* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_vfs_mp3(p_v_f_s &C.ma_vfs, p_file_path charptr, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_vfs_vorbis(ma_vfs* pVFS, const char* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_vfs_vorbis(p_v_f_s &C.ma_vfs, p_file_path charptr, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_vfs_wav_w(ma_vfs* pVFS, const wchar_t* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_vfs_wav_w(p_v_f_s &C.ma_vfs, p_file_path &C.wchar_t, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_vfs_flac_w(ma_vfs* pVFS, const wchar_t* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_vfs_flac_w(p_v_f_s &C.ma_vfs, p_file_path &C.wchar_t, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_vfs_mp3_w(ma_vfs* pVFS, const wchar_t* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_vfs_mp3_w(p_v_f_s &C.ma_vfs, p_file_path &C.wchar_t, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_vfs_vorbis_w(ma_vfs* pVFS, const wchar_t* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_vfs_vorbis_w(p_v_f_s &C.ma_vfs, p_file_path &C.wchar_t, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_file_wav(const char* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_file_wav(p_file_path charptr, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_file_flac(const char* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_file_flac(p_file_path charptr, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_file_mp3(const char* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_file_mp3(p_file_path charptr, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_file_vorbis(const char* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_file_vorbis(p_file_path charptr, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_file_wav_w(const wchar_t* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_file_wav_w(p_file_path &C.wchar_t, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_file_flac_w(const wchar_t* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_file_flac_w(p_file_path &C.wchar_t, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_file_mp3_w(const wchar_t* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_file_mp3_w(p_file_path &C.wchar_t, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_result ma_decoder_init_file_vorbis_w(const wchar_t* pFilePath, const ma_decoder_config* pConfig, ma_decoder* pDecoder);
fn C.ma_decoder_init_file_vorbis_w(p_file_path &C.wchar_t, p_config &C.ma_decoder_config, p_decoder &C.ma_decoder) Result

// MA_API ma_encoder_config ma_encoder_config_init(ma_resource_format resourceFormat, ma_format format, ma_uint32 channels, ma_uint32 sampleRate);
fn C.ma_encoder_config_init(resource_format C.ma_resource_format, format Format, channels u32, sample_rate u32) C.ma_encoder_config

// MA_API ma_result ma_encoder_init(ma_encoder_write_proc onWrite, ma_encoder_seek_proc onSeek, void* pUserData, const ma_encoder_config* pConfig, ma_encoder* pEncoder);
fn C.ma_encoder_init(on_write C.ma_encoder_write_proc, on_seek C.ma_encoder_seek_proc, p_user_data voidptr, p_config &C.ma_encoder_config, p_encoder &C.ma_encoder) Result

// MA_API ma_result ma_encoder_init_file(const char* pFilePath, const ma_encoder_config* pConfig, ma_encoder* pEncoder);
fn C.ma_encoder_init_file(p_file_path charptr, p_config &C.ma_encoder_config, p_encoder &C.ma_encoder) Result

// MA_API ma_result ma_encoder_init_file_w(const wchar_t* pFilePath, const ma_encoder_config* pConfig, ma_encoder* pEncoder);
fn C.ma_encoder_init_file_w(p_file_path &C.wchar_t, p_config &C.ma_encoder_config, p_encoder &C.ma_encoder) Result

// MA_API void ma_encoder_uninit(ma_encoder* pEncoder);
fn C.ma_encoder_uninit(p_encoder &C.ma_encoder)

// MA_API ma_uint64 ma_encoder_write_pcm_frames(ma_encoder* pEncoder, const void* pFramesIn, ma_uint64 frameCount);
fn C.ma_encoder_write_pcm_frames(p_encoder &C.ma_encoder, p_frames_in voidptr, frame_count u64) u64

// MA_API ma_waveform_config ma_waveform_config_init(ma_format format, ma_uint32 channels, ma_uint32 sampleRate, ma_waveform_type type, double amplitude, double frequency);
fn C.ma_waveform_config_init(format Format, channels u32, sample_rate u32, typ C.ma_waveform_type, amplitude f64, frequency f64) C.ma_waveform_config

// MA_API ma_result ma_waveform_init(const ma_waveform_config* pConfig, ma_waveform* pWaveform);
fn C.ma_waveform_init(p_config &C.ma_waveform_config, p_waveform &C.ma_waveform) Result

// MA_API void ma_waveform_uninit(ma_waveform* pWaveform);
fn C.ma_waveform_uninit(p_waveform &C.ma_waveform)

// MA_API ma_uint64 ma_waveform_read_pcm_frames(ma_waveform* pWaveform, void* pFramesOut, ma_uint64 frameCount);
fn C.ma_waveform_read_pcm_frames(p_waveform &C.ma_waveform, p_frames_out voidptr, frame_count u64) u64

// MA_API ma_result ma_waveform_seek_to_pcm_frame(ma_waveform* pWaveform, ma_uint64 frameIndex);
fn C.ma_waveform_seek_to_pcm_frame(p_waveform &C.ma_waveform, frame_index u64) Result

// MA_API ma_result ma_waveform_set_amplitude(ma_waveform* pWaveform, double amplitude);
fn C.ma_waveform_set_amplitude(p_waveform &C.ma_waveform, amplitude f64) Result

// MA_API ma_result ma_waveform_set_frequency(ma_waveform* pWaveform, double frequency);
fn C.ma_waveform_set_frequency(p_waveform &C.ma_waveform, frequency f64) Result

// MA_API ma_result ma_waveform_set_type(ma_waveform* pWaveform, ma_waveform_type type);
fn C.ma_waveform_set_type(p_waveform &C.ma_waveform, typ C.ma_waveform_type) Result

// MA_API ma_result ma_waveform_set_sample_rate(ma_waveform* pWaveform, ma_uint32 sampleRate);
fn C.ma_waveform_set_sample_rate(p_waveform &C.ma_waveform, sample_rate u32) Result

// MA_API ma_noise_config ma_noise_config_init(ma_format format, ma_uint32 channels, ma_noise_type type, ma_int32 seed, double amplitude);
fn C.ma_noise_config_init(format Format, channels u32, typ C.ma_noise_type, seed int, amplitude f64) C.ma_noise_config

// MA_API ma_result ma_noise_init(const ma_noise_config* pConfig, ma_noise* pNoise);
fn C.ma_noise_init(p_config &C.ma_noise_config, p_noise &C.ma_noise) Result

// MA_API void ma_noise_uninit(ma_noise* pNoise);
fn C.ma_noise_uninit(p_noise &C.ma_noise)

// MA_API ma_uint64 ma_noise_read_pcm_frames(ma_noise* pNoise, void* pFramesOut, ma_uint64 frameCount);
fn C.ma_noise_read_pcm_frames(p_noise &C.ma_noise, p_frames_out voidptr, frame_count u64) u64

// MA_API ma_result ma_noise_set_amplitude(ma_noise* pNoise, double amplitude);
fn C.ma_noise_set_amplitude(p_noise &C.ma_noise, amplitude f64) Result

// MA_API ma_result ma_noise_set_seed(ma_noise* pNoise, ma_int32 seed);
fn C.ma_noise_set_seed(p_noise &C.ma_noise, seed int) Result

// MA_API ma_result ma_noise_set_type(ma_noise* pNoise, ma_noise_type type);
fn C.ma_noise_set_type(p_noise &C.ma_noise, typ C.ma_noise_type) Result
