// NOTE this file is auto-generated by chew
module miniaudio

//
// Manual tweaks to get the V compiler to shut up
//

// C typedef aliases used

pub type C.ma_mutex = C.ma_handle

[typedef]
pub struct C.ma_event {}

[typedef]
pub struct C.ma_semaphore {}
