// NOTE this file is auto-generated by chew
module miniaudio

//
// Manual tweaks to get the V compiler to shut up
//

// C typedef aliases used

@[typedef]
pub struct C.pthread_mutex_t {}

pub type C.ma_pthread_mutex_t = C.pthread_mutex_t

@[typedef]
pub struct C.pthread_cond_t {}

pub type C.ma_pthread_cond_t = C.pthread_cond_t

// ma_mutex -> ma_pthread_mutex_t -> C.ma_pthread_mutex_t
pub type C.ma_mutex = C.pthread_mutex_t

@[typedef]
pub struct C.ma_event {
pub mut:
	value u32
	@lock C.ma_pthread_mutex_t
	cond  C.ma_pthread_cond_t
}

@[typedef]
pub struct C.ma_semaphore {
pub mut:
	value int
	@lock C.ma_pthread_mutex_t
	cond  C.ma_pthread_cond_t
}
