name: Code CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  ubuntu-tcc:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      VFLAGS: -cc tcc -no-retry-compilation
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - name: Build local v
        run: make -j4 && sudo ./v symlink

      - name: Checkout miniaudio
        uses: actions/checkout@v2
        with:
          path: miniaudio

      - name: Link local miniaudio folder in ~/.vmodules/miniaudio
        run: |
          cd miniaudio
          mkdir -p ~/.vmodules
          ln -s $(pwd) ~/.vmodules/miniaudio

      - name: Test code formatting
        run: |
          cd miniaudio
          v test-fmt
          v fmt -verify .

      # - name: Run tests
      #   run: v -d ci test miniaudio

